### PR TITLE
Fixing Issue #53

### PR DESCRIPTION
**Pull request by math-and-data**
Need int64 as default.
See https://github.com/tensorflow/lucid/issues/53

### CODE REVIEW

**Comment by math-and-data** [comment]
I signed it!

**Comment by math-and-data** [comment]
I signed it!

**Comment by math-and-data** [comment]
Great, I'm going to close this out (used uuids instead).

**Comment by ludwigschubert** [comment]
Jupp! Thanks for bringing it up, and sorry we couldn’t go with your PR—I feel UUIDs are a better match for guaranteeing unique names.

**Comment by math-and-data** [comment]
No problem - mine was really just a local quick fix. Yours is definitely the more elegant solution.

**Pull request closed without merging**
